--- #YAML:1.0
name:                TL1Toolkit
version:             0.01
abstract:            Utility functions for interacting with TL1 equipment
license:             ~
author:              
    - Ronald van der Pol <rvdp@sara.nl>, Andree Toonk <andree@sara.nl>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Date::Manip:                   0
    Net::Telnet:                   0
    Thread::Queue::Any:            0
    threads::shared:               0
    Time::localtime:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
